package com.jimi.adct_server.comm.model;

import com.jimi.adct_server.comm.model.base.BaseAdctLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdctLog extends BaseAdctLog<AdctLog> {
	public static final AdctLog dao = new AdctLog().dao();
}
