package com.jimi.adct_server.comm.model;

import com.jimi.adct_server.comm.model.base.BaseAdct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Adct extends BaseAdct<Adct> {
	public static final Adct dao = new Adct().dao();
}
