package com.jimi.adct_server.comm.model;

import com.jimi.adct_server.comm.model.base.BaseGpsUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpsUser extends BaseGpsUser<GpsUser> {
	public static final GpsUser dao = new GpsUser().dao();
}
