package com.jimi.adct_server.comm.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     MssqlMappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class MssqlMappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("Gps_User", "UserId", GpsUser.class);
	}
}

