package com.jimi.adct_server.comm.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     MysqlMappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class MysqlMappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("action_log", "id", ActionLog.class);
		arp.addMapping("adct", "id", Adct.class);
		arp.addMapping("adct_log", "id", AdctLog.class);
		arp.addMapping("package_log", "id", PackageLog.class);
		arp.addMapping("system_log", "id", SystemLog.class);
	}
}

