package com.jimi.adct_server.comm.model;

import com.jimi.adct_server.comm.model.base.BasePackageLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PackageLog extends BasePackageLog<PackageLog> {
	public static final PackageLog dao = new PackageLog().dao();
}
